### ISSUE TITLE
Move `org.openrewrite.java.apache.httpclient4.MigrateDefaultHttpClient` to `rewrite-apache`

### ISSUE THREAD

**Issue by JLLeitschuh** [openrewrite/rewrite-apache#1]
## What problem are you trying to solve?

`org.openrewrite.java.apache.httpclient4.MigrateDefaultHttpClient` seems to be in the wrong place as it isn't related to Spring.

## Describe the solution you'd like

It would make sense to move the `org.openrewrite.java.apache.httpclient4.MigrateDefaultHttpClient` to a dedicated `rewrite-apache` package.

**Comment by timtebeek** [comment]
Completed this migration using [this reference](https://stackoverflow.com/a/11426261/53444), and moving the paths to match the new target location.

**Comment by timtebeek** [comment]
Still to do:

- [ ] remove references from rewrite-spring and rewrite-migrate-java
- [ ] update rewrite-docs and rewrite-recipe-markdown-generator
- [ ] run weekly internal vulnerability scans against rewrite-apache
- [ ] add quick regex recipe for folks that want to adopt the new recipe paths
