### ISSUE TITLE
Build issues after ApacheHttpClient 5.x upgrade

### ISSUE THREAD

**Issue by ankilosaurus** [openrewrite/rewrite-apache#42]
## What version of OpenRewrite are you using?
I am using

rewrite-recipe-bom 2.21.1
rewrite-maven-plugin 5.43.0

## How are you running OpenRewrite?

I am using the Maven plugin, and my project is a multi module project.
```
./mvnw -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-spring:RELEASE -Drewrite.activeRecipes=org.openrewrite.java.spring.framework.UpgradeSpringFramework_6_1 -Drewrite.exportDatatables=true
```

## What is the smallest, simplest way to reproduce the problem?

Run recipe on project with apache httpcomponents 4.x

## What did you expect to see?
Recipe to get applied successfully and project builds successfully

## What did you see instead?
Recipe got applied successfully but project fails to build afterwards due to transformations are not fully applied. 

## What is the full stack trace of any errors you encountered?

Following are the build errors observed and how I resolved those -

- [ ] `cannot find symbol [ERROR] symbol: class HttpRequestBase` -> replaced manually with HttpUriRequestBase
- [ ] `cannot find symbol [ERROR] symbol: method setSocketConfig(org.apache.hc.core5.http.HttpHost,org.apache.hc.core5.http.io.SocketConfig) [ERROR] location: variable connectionManager of type org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager` -> replaced manually with SetDefaultSocketConfig wo/ host argument
- [ ] `cannot find symbol [ERROR] symbol: method getAllHeaders() [ERROR] location: variable response of type org.apache.hc.client5.http.impl.classic.CloseableHttpResponse` -> replaced manually with getHeaders()
- [ ] `cannot find symbol [ERROR] symbol: method shutdown() [ERROR] location: variable connectionManager of type org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager` -> removed call to shutdown() manually
- [ ] `incompatible types: java.lang.String cannot be converted to org.apache.hc.core5.http.Header` -> replaced manually to String
- [ ] `cannot find symbol [ERROR] symbol: method getValue() [ERROR] location: variable contentType of type java.lang.String` -> removed call to getValue()
- [ ] `package org.apache.hc.core5.http.client.fluent does not exist` -> manual import `org.apache.hc.client5.http.fluent`
- [ ] `package org.apache.hc.core5.http.io.entity.mime` does not exist -> manual import `org.apache.hc.client5.http.entity.mime`
- [ ] `cannot find symbol [ERROR] symbol: method Put(java.lang.String) [ERROR] location: class org.apache.hc.client5.http.fluent.Request [ERROR]` -> manually change all Get/Put/Post/Delete calls to lowercase 
- [ ] cannot find symbol [ERROR] symbol: method getEntity() -> manually cast response to ClassicHttpResponse
- [ ] `unreported exception org.apache.hc.core5.http.ParseException; must be caught or declared to be thrown` -> manual import org.apache.hc.core5.http.ParseException and catch exception
- [ ] `cannot find symbol [ERROR] symbol: class Consts [ERROR] location: package org.apache.hc.core5.http` -> import java.nio.charset.StandardCharsets and replace Consts.UTF_8 with StandardCharsets.UTF_8
- [ ] `no suitable constructor found for UsernamePasswordCredentials(java.lang.String,java.lang.String) [ERROR] constructor org.apache.hc.client5.http.auth.UsernamePasswordCredentials.UsernamePasswordCredentials(java.security.Principal,char[]) is not applicable [ERROR] (argument mismatch; java.lang.String cannot be converted to java.security.Principal) [ERROR] constructor org.apache.hc.client5.http.auth.UsernamePasswordCredentials.UsernamePasswordCredentials(java.lang.String,char[]) is not applicable [ERROR] (argument mismatch; java.lang.String cannot be converted to char[])` -> manually changed password parameter to password.toCharArray()
- [ ]  `cannot find symbol [ERROR] symbol: method setCredentials(org.apache.hc.client5.http.auth.AuthScope,org.apache.hc.client5.http.auth.UsernamePasswordCredentials) [ERROR] location: variable credsProvider of type org.apache.hc.client5.http.auth.CredentialsProvider` -> manually changed to BasicCredentialsProvider

**Comment by timtebeek** [comment]
Thanks a lot for the detailed report @ankilosaurus ! This is invaluable feedback to complete that migration. Reading the above list it seems that at least some of those, like the missing imports, would be straightforward to add to the existing recipe:
https://github.com/openrewrite/rewrite-apache/blob/e4dd910203d8d8674ed7dfcd346696f5bf9410b1/src/main/resources/META-INF/rewrite/apache-httpclient-5.yml#L20-L26

Would you be open to adding a few of those missing steps there in a draft PR?

**Comment by ankilosaurus** [comment]
closing for now. will open more granular issues and propose fixes.
