### ISSUE TITLE
Migrate from Apache Commons Collections to Commons Collections4

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-apache#5]
Teams often are using `org.apache.commons.collections` instead of `org.apache.commons.collections4` so I would like a recipe that migrates to `org.apache.commons.collections4`.

I see the recipe as:

* `org.apache.commons.collections` -> `org.apache.commons.collections4`
* If `commons-collections` is present in the pom file, remove it.
* If `commons-collections4` is *NOT* present in the pom and/or dependency tree add it.

**Comment by bsmahi** [comment]
Hi @timtebeek Can I pickup this one for creating a recipe for removeDependency of `commons-collections` and addDependency `commons-collections4` in the pom.xml

Thanks,
Mahi

**Comment by timtebeek** [comment]
Thanks for the offer to help @bsmahi ! I think this had already been picked up and completed by @sullis in https://github.com/openrewrite/rewrite-apache/pull/10

If not I'd love to hear what else we might need!
